# CausalHES Configuration File
# Configuration for Causally-Inspired Household Energy Segmentation

# Model Architecture Configuration
model:
  # Number of clusters for household segmentation
  n_clusters: 5
  
  # Input shapes
  load_input_shape: [24, 1]      # [timesteps, features] for load profiles
  weather_input_shape: [24, 2]   # [timesteps, features] for weather data (temp, humidity)
  
  # CSSAE Architecture
  cssae:
    # Encoder dimensions
    load_embedding_dim: 64        # Mixed load embedding dimension
    weather_embedding_dim: 32     # Weather embedding dimension
    
    # Source separation dimensions
    base_dim: 32                  # Base load embedding dimension (used for clustering)
    weather_effect_dim: 16        # Weather effect embedding dimension
    
    # Separation method: "residual" or "multi_head"
    separation_method: "residual"
    
    # Encoder architecture
    load_encoder:
      n_layers: 3
      dropout_rate: 0.1
    
    weather_encoder:
      n_layers: 2
      dropout_rate: 0.1
    
    # Decoder architecture
    decoders:
      hidden_dim_base: 64
      hidden_dim_weather: 32
  
  # DEC parameters
  dec:
    alpha: 1.0                    # Degrees of freedom for Student's t-distribution

# Loss Function Configuration
loss:
  # Loss weights
  reconstruction_weight: 1.0      # Weight for reconstruction loss
  causal_weight: 0.1             # Weight for causal independence loss
  clustering_weight: 0.5         # Weight for clustering loss
  
  # Causal loss components
  causal_loss:
    mi_weight: 1.0               # Mutual information weight
    adversarial_weight: 0.5      # Adversarial independence weight
    dcor_weight: 0.3             # Distance correlation weight

# Training Configuration
training:
  # CSSAE Pre-training
  cssae_pretraining:
    epochs: 100
    batch_size: 32
    learning_rate: 0.001
    validation_split: 0.1
    patience: 10
    
    # Curriculum learning
    curriculum_learning: true
    warmup_epochs: 10
  
  # Joint Training (CSSAE + DEC)
  joint_training:
    epochs: 50
    batch_size: 32
    learning_rate: 0.0005
    tolerance: 0.001
    update_interval: 1
  
  # Optimization
  optimizer: "adam"
  
  # Regularization
  dropout_rate: 0.1
  l2_regularization: 0.0001

# Data Configuration
data:
  # Dataset parameters
  dataset_name: "household_energy"
  data_dir: "data/"
  
  # Data preprocessing
  normalization: "minmax"         # "minmax", "standard", or "none"
  sequence_length: 24             # Hours in a day
  
  # Train/validation/test split
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15
  
  # Data augmentation (for training robustness)
  augmentation:
    enabled: false
    noise_level: 0.01
    time_shift_range: 2

# Evaluation Configuration
evaluation:
  # Metrics to compute
  clustering_metrics:
    - "accuracy"
    - "nmi"
    - "ari"
    - "silhouette_score"
    - "calinski_harabasz_score"
    - "davies_bouldin_score"
  
  source_separation_metrics:
    - "independence_score"
    - "reconstruction_quality"
    - "separation_quality"
  
  # Evaluation settings
  sample_size_for_evaluation: 1000
  bootstrap_runs: 10

# Experiment Configuration
experiment:
  # Experiment name and output
  name: "causal_hes_experiment"
  output_dir: "experiments/results/causal_hes"
  
  # Random seed for reproducibility
  random_seed: 42
  
  # Logging
  logging:
    level: "INFO"
    log_to_file: true
    log_to_console: true
  
  # Checkpointing
  checkpointing:
    enabled: true
    save_best_only: true
    monitor: "val_loss"
    mode: "min"
  
  # Visualization
  visualization:
    enabled: true
    save_plots: true
    plot_format: "png"
    dpi: 300

# Baseline Comparison Configuration
baselines:
  # Which baselines to run
  enabled_baselines:
    - "kmeans_load"
    - "pca_kmeans"
    - "dec_load"
    - "concat_kmeans"
    - "weather_fused_dec"  # Original DSMC approach
  
  # Baseline-specific parameters
  kmeans:
    n_init: 10
    max_iter: 300
  
  pca:
    n_components: 10
  
  dec:
    embedding_dim: 32
    pretraining_epochs: 30
    clustering_epochs: 20

# Ablation Study Configuration
ablation:
  # Which ablation studies to run
  enabled_studies:
    - "no_causal_constraints"
    - "different_separation_methods"
    - "different_loss_weights"
    - "different_architectures"
  
  # Ablation-specific parameters
  studies:
    no_causal_constraints:
      causal_weight: 0.0
    
    different_separation_methods:
      methods: ["residual", "multi_head"]
    
    different_loss_weights:
      causal_weights: [0.01, 0.05, 0.1, 0.2, 0.5]
      clustering_weights: [0.1, 0.3, 0.5, 0.7, 1.0]
    
    different_architectures:
      base_dims: [16, 32, 64]
      load_embedding_dims: [32, 64, 128]

# Hardware Configuration
hardware:
  # GPU settings
  use_gpu: true
  gpu_memory_growth: true
  mixed_precision: false
  
  # Parallel processing
  n_jobs: -1                      # Number of parallel jobs (-1 for all cores)
  
  # Memory management
  batch_size_auto_scaling: true
  max_memory_usage: 0.8          # Maximum fraction of available memory to use

# Advanced Configuration
advanced:
  # Numerical stability
  epsilon: 1e-8
  
  # Gradient clipping
  gradient_clipping:
    enabled: true
    max_norm: 1.0
  
  # Learning rate scheduling
  lr_scheduling:
    enabled: true
    scheduler: "reduce_on_plateau"
    factor: 0.5
    patience: 5
    min_lr: 1e-6
  
  # Early stopping
  early_stopping:
    enabled: true
    patience: 15
    restore_best_weights: true
  
  # Model ensemble (for improved robustness)
  ensemble:
    enabled: false
    n_models: 5
    voting_strategy: "soft"
